    - name: Pull Radarr container image
      docker_image:
        name: linuxserver/radarr
        tag: latest
        source: pull

    - name: Create Radarr container
      docker_container:
        name: radarr
        image: linuxserver/radarr
        state: started
        recreate: yes
        container_default_behavior: "no_defaults"
        ports:
          - "7878:7878"
        volumes:
          - "/mnt/radarr:/config"
          - "/mnt/movies:/movies"
        env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Amsterdam