- name: Run multiple playbooks
  hosts: all

  tasks:
    - name: Import tasks from playbook1.yml
      become: true
      import_tasks: app_docker.yml
    - name: Import tasks from playbook2.yml
      become: true
      import_tasks: container_radarr_start.yml