- name: Secure Machines
  hosts: test
  become: true
  become_user: root
  remote_user: ansible

  tasks:
    # Install and configure UFW
    - name: Install UFW
      apt:
        name: ufw
        state: present
    - name: Open SSH port
      ufw:
        rule: allow
        port: ssh
    - name: Open HTTP port
      ufw:
        rule: allow
        port: http
    - name: Open HTTPS port
      ufw:
        rule: allow
        port: https
    - name: Reload firewall
      ufw:
        state: reloaded
    - name: Turn on firewall
      ufw:
        state: enabled

    # Disable PermitRootLogin
    - name: Disable PermitRootLogin
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
        
    # Disable PasswordAuthentication
    - name: Disable PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes
        validate: 'sshd -t'
        notify: restart sshd

    - name: Disable root user
      command: usermod -p '!' root

    # Create rsc user and add to sudo group
    - name: Create rsc user
      user:
        name: rsc
        state: present
        append: yes
        groups: sudo
        shell: /bin/bash
        
    # Create home folder for rsc user
    - name: Create home folder for rsc user
      file:
        path: /home/rsc
        state: directory
        owner: rsc
        group: rsc
        mode: '0755'

    # Add authorized key for rsc user
    - name: Add authorized key for rsc user
      authorized_key:
        user: rsc
        key: "{{ lookup('file', '/path/to/authorized_key.pub') }}"
        state: present

    - name: Install Fail2ban
      apt:
        name: fail2ban
        state: presentop
    - name: Configure Fail2ban
      template:
        src: fail2ban.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify: restart fail2ban
    - name: Enable and start Fail2ban
      systemd:
        name: fail2ban
        state: started
        enabled: yes