- name: Secure Machines
  hosts: test
  become: true
  become_user: root
  remote_user: ansible

  tasks:
  
    # Disable IPv6
    - name: Disable IPv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present
        sysctl_set: yes
      notify:
        - Restart Network

    # Install and configure UFW
    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Disable UFW
      ufw:
        state: disabled

    - name: Reset UFW
      ufw:
        state: reset

    - name: Open SSH port
      ufw:
        rule: allow
        port: ssh

    - name: Open HTTP port
      ufw:
        rule: allow
        port: http

    - name: Open HTTPS port
      ufw:
        rule: allow
        port: https

    - name: Reload firewall
      ufw:
        state: reloaded

    - name: Turn on firewall
      ufw:
        state: enabled

    # Disable PermitRootLogin
    - name: Disable PermitRootLogin
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify:
        - Restart SSH

    # Disable PasswordAuthentication
    - name: Disable PasswordAuthentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes
      notify:
        - Restart SSH

    # Disable ChallengeResponseAuthentication
    - name: Disable ChallengeResponseAuthentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
        state: present
        backup: yes
      notify:
        - Restart SSH

    # Remove 50-cloud-init.conf
    - name: Remove 50-cloud-init.conf
      file:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        state: absent
      notify:
        - Restart SSH

    # Remove Disable root user
    - name: Disable root user
      command: usermod -p '!' root

    # Create rsc user and add to sudo group
    - name: Create rsc user
      user:
        name: rsc
        state: present
        append: yes
        groups: sudo
        shell: /bin/bash
        
    # Create home folder for rsc user
    - name: Create home folder for rsc user
      file:
        path: /home/rsc
        state: directory
        owner: rsc
        group: rsc
        mode: '0755'

    # Add authorized key for rsc user
    - name: Add authorized key for rsc user
      authorized_key:
        user: rsc
        key: "{{ lookup('file', 'authorized_key.pub') }}"
        state: present


    - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes


  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted

    - name: Restart network
      service:
        name: systemd-networkd
        state: restarted
      async: 120
      poll: 0
      register: net_restarting