---
- name: Setup Docker Swarm
  hosts: all
  become: true
  tasks:
    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present
        
    - name: Add nodes
      docker_swarm:
        state: join
        advertise_addr: 192.168.1.2
        join_token: SWMTKN-1--xxxxx
        remote_addrs: [ 'vm01:2377' ]