---
- name: Setup Docker Swarm
  hosts: all
  become: true
  tasks:
    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present

    - name: Add nodes
      docker_swarm:
        state: join
        advertise_addr: vm01
        join_token: SWMTKN-1--4848784325
        remote_addrs: [ 'vm01:2377' ]