---
- name: Install Docker Swarm
  hosts: all
  become: true
  tasks:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

- name: Join nodes to Docker Swarm
  hosts: swarm
  become: true
  vars:
    swarm_token: "{{ hostvars[groups['swarm_manager'][0]]['swarm_token'] }}"
    swarm_ip: "{{ hostvars[groups['swarm_manager'][0]]['ansible_host'] }}"
  tasks:
    - name: Join worker nodes to Docker Swarm
      shell: docker swarm join --token {{ swarm_token }} {{ swarm_ip }}:2377
      when: "'swarm_worker' in group_names"

    - name: Initialize manager node for Docker Swarm
      shell: docker swarm init --advertise-addr {{ swarm_ip }}
      when: "'swarm_manager' in group_names"
      register: swarm_init

    - name: Save Docker Swarm join token
      set_fact:
        swarm_token: "{{ swarm_init.stdout_lines[-2] }}"

    - name: Save Docker Swarm manager IP address
      set_fact:
        swarm_ip: "{{ ansible_host }}"
      when: "'swarm_manager' in group_names"
