- name: Secure Machines
  hosts: all
  become: true

  tasks:
    # Install and configure UFW
    - name: Install UFW
      apt:
        name: ufw
        state: present
    - name: Open SSH port
      ufw:
        rule: allow
        port: ssh
    - name: Open HTTP port
      ufw:
        rule: allow
        port: http
    - name: Open HTTPS port
      ufw:
        rule: allow
        port: https
    - name: Reload firewall
      ufw:
        state: reloaded
    - name: Turn on firewall
      ufw:
        state: enabled

    # Disable PermitRootLogin
    - name: Configure SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
        validate: 'sshd -t'
        notify: restart sshd

    # Disable PasswordAuthentication
    - name: Disable PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes
        validate: 'sshd -t'
        notify: restart sshd

    - name: Disable root user
      command: usermod -p '!' root

    # Create rsc user and add to sudo group
    - name: Create rsc user
      user:
        name: rsc
        state: present
        append: yes
        groups: sudo
        shell: /bin/bash
        
    # Create home folder for rsc user
    - name: Create home folder for rsc user
      file:
        path: /home/rsc
        state: directory
        owner: rsc
        group: rsc
        mode: '0755'

