- name: Secure Machines
  hosts: all
  become: true

  tasks:
    - name: Turn on firewall
      firewalld:
        state: enabled
        immediate: yes

    - name: Open SSH port
      firewalld:
        service: ssh
        permanent: true
        immediate: yes
    - name: Open HTTP port
      firewalld:
        service: http
        permanent: true
        immediate: yes

    - name: Open HTTPS port
      firewalld:
        service: https
        permanent: true
        immediate: yes
