- name: Secure Machines
  hosts: all
  become: true

  tasks:
    # Install and configure UFW
    - name: Install UFW
      apt:
        name: ufw
        state: present
    - name: Reload firewall
      ufw:
        state: reloaded
    - name: Open SSH port
      ufw:
        rule: allow
        port: ssh
    - name: Open HTTP port
      ufw:
        rule: allow
        port: http
    - name: Open HTTPS port
      ufw:
        rule: allow
        port: https
    - name: Turn on firewall
      ufw:
        state: enabled

    # Disable PermitRootLogin
    - name: Configure SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
        validate: 'sshd -t'
        notify: restart sshd

    # Disable PasswordAuthentication
    - name: Disable PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes
        validate: 'sshd -t'
        notify: restart sshd

    - name: Disable root user
      command: usermod -p '!' root

    - name: Delete rsc user
      user:
        name: rsc
        state: absent

    # Create break-glass user and add to sudo group
    - name: Create break-glass user
      user:
        name: break-glass
        state: present
        append: yes
        groups: sudo
    # Create home folder for break-glass user
    - name: Create home folder for break-glass user
      file:
        path: /home/break-glass
        state: directory
        owner: break-glass
        group: break-glass
        mode: '0755'

